#!/usr/bin/env python3
"""
Test script for video generation from upscaled frames.
This script demonstrates how to create a video from frames generated by StreamDiffVSR
and preserve audio from the original video.
"""

import os
import cv2
import subprocess

def create_video_from_frames(frames_dir, output_video_path, fps, width, height, original_video_path=None):
    """Create a video from frames and optionally add audio from original video."""
    
    # Get sorted list of frame files
    frame_files = sorted([f for f in os.listdir(frames_dir) if f.endswith('.png')])
    if not frame_files:
        print(f"Error: No PNG frames found in {frames_dir}")
        return False
    
    print(f"Creating video from {len(frame_files)} frames...")
    print(f"Output dimensions: {width}x{height} @ {fps} fps")
    
    # Create video from frames using OpenCV
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    video_writer = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))
    
    for i, frame_file in enumerate(frame_files):
        frame_path = os.path.join(frames_dir, frame_file)
        frame = cv2.imread(frame_path)
        if frame is None:
            print(f"Warning: Could not read frame {frame_file}")
            continue
        video_writer.write(frame)
        
        if i % 50 == 0:
            print(f"Processed {i+1}/{len(frame_files)} frames...")
    
    video_writer.release()
    print(f"Video created: {output_video_path}")
    
    # If original video has audio, extract and merge it
    if original_video_path and os.path.exists(original_video_path):
        print("Extracting audio from original video...")
        
        # Create temporary audio file
        temp_audio_path = os.path.join(frames_dir, "temp_audio.aac")
        
        # Extract audio using ffmpeg
        try:
            # First, extract audio
            extract_cmd = [
                'ffmpeg', '-i', original_video_path,
                '-vn', '-acodec', 'copy',
                temp_audio_path, '-y'
            ]
            subprocess.run(extract_cmd, check=True, capture_output=True)
            
            # Create final video with audio
            final_video_path = output_video_path.replace('.mp4', '_with_audio.mp4')
            merge_cmd = [
                'ffmpeg', '-i', output_video_path,
                '-i', temp_audio_path,
                '-c:v', 'copy', '-c:a', 'aac',
                '-map', '0:v:0', '-map', '1:a:0',
                '-shortest',
                final_video_path, '-y'
            ]
            subprocess.run(merge_cmd, check=True, capture_output=True)
            
            # Clean up temporary files
            os.remove(temp_audio_path)
            os.remove(output_video_path)  # Remove video without audio
            os.rename(final_video_path, output_video_path)  # Rename to original name
            
            print(f"Video with audio created: {output_video_path}")
            
        except subprocess.CalledProcessError as e:
            print(f"Warning: Could not merge audio: {e}")
            print("Video created without audio.")
        except FileNotFoundError:
            print("Warning: ffmpeg not found. Video created without audio.")
    
    return True

if __name__ == "__main__":
    # Example usage
    print("Video Generation Test Script")
    print("=============================")
    print("This script demonstrates how to create a video from frames generated by StreamDiffVSR.")
    print("\nUsage example:")
    print("""
    # After running inference.py on a video file, you'll have frames in:
    frames_dir = "/path/to/output/frames/"
    
    # Get video properties (you can use ffprobe or extract_frames_from_video function)
    fps = 24.0
    width = 2048  # 4x upscale from 512
    height = 2816  # 4x upscale from 704
    
    # Create video
    create_video_from_frames(
        frames_dir, 
        "/path/to/output/video_upscaled.mp4",
        fps, width, height,
        "/path/to/original/video.mp4"
    )
    """)
    
    # You can also run this as a standalone test by modifying the paths below
    test_frames_dir = "/home/dali/Videos/output/2026-01-11-16"
    test_output_video = "/home/dali/Videos/output/2026-01-11-16_upscaled.mp4"
    test_original_video = "/home/dali/Videos/input/2026-01-11-16.mp4"
    
    if os.path.exists(test_frames_dir):
        print(f"\nTest directory exists: {test_frames_dir}")
        print("To run the test, uncomment the code below and adjust paths as needed.")
        """
        # Uncomment to run test
        fps = 24.0
        width = 2048  # 4x upscale from 512
        height = 2816  # 4x upscale from 704
        
        success = create_video_from_frames(
            test_frames_dir, test_output_video, fps, width, height, test_original_video
        )
        
        if success:
            print("Test completed successfully!")
        else:
            print("Test failed.")
        """